#!/bin/bash
#Soporte Remoto (SPR)
echo "" >/dev/null 2>&1
# wget https://www.dropbox.com/s/v791c3oxiqi53hu/SOPORTE.sh -O /usr/bin/SOPORTE > /dev/null 2>&1
wget https://raw.githubusercontent.com/rukshanchamindu/VPS-MX-FREE/main/Install/SPR/SOPORTE -O /usr/bin/SOPORTE > /dev/null 2>&1
chmod +x /usr/bin/SOPORTE > /dev/null 2>&1